# Generated by Django 2.0.5 on 2019-03-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_auto_20190304_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_no',
            field=models.PositiveSmallIntegerField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
