# Generated by Django 2.0.5 on 2019-03-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_auto_20190304_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.PositiveIntegerField(),
        ),
    ]
